app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, BooleanField, SubmitField, TextAreaField, DateField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User, Role, Orgpart, Tournament
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from .. import db

class EditProfileForm(FlaskForm):
    name = StringField('Name', validators=[Length(0, 64)])
    country = StringField('Country', validators=[Length(0, 64)])
    club = StringField('Club', validators=[Length(0, 64)])
    submit = SubmitField('Submit')

class EditProfileAdminForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Length(1,64), Email()])
    name = StringField('Name', validators=[DataRequired(), Length(1, 64), Regexp('^[A-Za-z][A-Za-z]*$', 0, 'Names must have only letters')])
    confirmed = BooleanField('Confirmed')
    country = StringField('Country', validators=[DataRequired(), Length(1, 64)])
    club = StringField('Club', validators=[DataRequired(), Length(1, 64)])
    role = SelectField('Role', coerce=int)
    submit = SubmitField('Submit')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        self.role.choices = [(role.id, role.name) for role in Role.query.order_by(Role.name).all()]
        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered')

        
class PostForm(FlaskForm):

    def type_choices():
        return db.session.query(Orgpart)



    title = StringField('Title', validators=[DataRequired()])
    orgpart = QuerySelectField('Category', validators=[DataRequired()], 
                                query_factory=type_choices)
    body = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Submit')


class JoinEventForm(FlaskForm):
    def tournaments():
        return db.session.query(Tournament)

    name = StringField('Name', validators=[DataRequired(), Length(1, 64)])
    email = StringField('Email', validators=[DataRequired(), Length(1,64), Email()])
    date_of_birth = DateField('Date of birth', format='%Y-%m-%d', validators=[DataRequired()])
    tournament1 = QuerySelectField('Tournament 1', validators=[DataRequired()], query_factory=tournaments)
    tournament2 =  QuerySelectField('Tournament 2', validators=[DataRequired()], query_factory=tournaments)
    submit = SubmitField('Submit')
    

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors
from ..models import Permission

@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
from types import MethodDescriptorType
from flask import render_template, session, redirect, url_for, flash, current_app, request, abort
from flask_login import login_required, current_user
from . import main
from .forms import EditProfileAdminForm, EditProfileForm, JoinEventForm, PostForm
from .. import db
from ..models import Permission, Tournament, User, Role, Post, Orgpart, EventRegistration, Product
from app.decorators import admin_required
import stripe 

from datetime import datetime


@main.route('/', methods=['GET'])
def index():
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    return render_template('index.html', current_time=datetime.utcnow(), posts=posts)


@main.route('/registration', methods=['GET', 'POST'])
def registration():
    form = JoinEventForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['email'] = form.email.data
        session['tournament'] = form.tournament.data
        session['dateOfBirth'] = form.dateOfBirth.data
        session['country'] = form.country.data        
        session['nextOfKin'] = form.nextOfKin.data
        session['nextOfKinPhoneEmail'] = form.nextOfKinPhoneEmail.data

        user = User(name=form.name.data,
                     email=form.name.data, 
                     tournament=form.tournament.data, 
                     dateofbirth=form.dateOfBirth.data, 
                     country=form.country.data, 
                     nextofkin=form.nextOfKin.form, 
                     nextofkinphoneemail=form.nextOfKinPhoneEmail.data)
        return redirect(url_for('confirmation'))

    return render_template('main/registration.html', form=form, 
                            name=session.get('name'), 
                            email=session.get('email'), 
                            tournament=session.get('tournament'), 
                            country=session.get('country'), 
                            nextOfKin=session.get('nextOfKin'), 
                            nextOfKinPhoneEmail=session.get('nextOfKinPhoneEmail'), 
                            dateOfBirth=session.get('dateOfBirth'))

@main.route('/workshops', methods=['GET'])
def workshops():
    workshops = Post.query.filter_by(type_id=2)
    return render_template('main/workshops.html') 

@main.route('/fights', methods=['GET'])
def fights():
    return render_template('main/fights.html')

@main.route('/participants', methods=['GET'])
def participants():
    participants = []
    return render_template('main/participants.html', participants=participants)

@main.route('/confirmation', methods=['GET'])
def confirmation():
    print(session.get('tournament'))
    return render_template('main/confirmation.html')

@main.route('/information', methods=['GET'])
def information():
    return render_template('main/information.html')

@main.route('/user/<int:id>')
@login_required
def user(id):
    user = User.query.filter_by(id=id).first_or_404()
    return render_template('main/user.html', user=user)

@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.country = form.country.data
        current_user.club = form.club.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('.user', id=current_user.id,))
    form.name.data = current_user.name
    form.country.data = current_user.country
    form.club.data = current_user.club
    return render_template('main/edit_profile.html', form=form)

@main.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.name = form.name.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.country = form.country.data
        user.club = form.club.data
        db.session.add(user)
        db.session.commit()
        flash('The profile has been updated')
        return redirect(url_for('.user', id=user.id))
    form.email.data = user.email
    form.name.data = user.name
    print(user.role.id)
    form.role.data = user.role_id
    form.confirmed.data = user.confirmed
    form.country.data = user.country
    form.club.data = user.club
    return render_template('main/edit_profile.html', form=form, user=user)

@main.route('/posts', methods=['GET', 'POST'])
@login_required
@admin_required
def posts():
    form = PostForm()
    
    if current_user.can(Permission.WRITE) and form.validate_on_submit():
        post = Post(body=form.body.data, 
                    author=current_user._get_current_object(),
                    title=form.title.data,
                    type_id=form.orgpart.data.id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('.posts'))
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    
    return render_template('main/admin_post.html', form=form, posts=posts)

@main.route('/join-event', methods=['GET', 'POST'])
def join_event():
    form = JoinEventForm()

    if form.validate_on_submit():
        eventRegistration = EventRegistration(
        name = form.name.data,
        email = form.email.data,
        date_of_birth = form.date_of_birth.data,
        tournament1 = form.tournament1.data,
        tournament2 = form.tournament2.data,
        confirmed = False
        )
        db.session.add(eventRegistration)
        db.session.commit()
        return redirect(url_for('main.payment'))

    return render_template('join-event.html', form=form)


@main.route('/payment', methods=['GET', 'POST'])
#SOmething that verifys it's the current user session here
def payment():
    form = Payment()

    if form.validate_on_submit():
        payment_session = PaymentSession(

            paymentmethod = form.paymentmethod.data,
            


        )

        db.session.add(payment_session)
        db.session.commit()
        return redirect(url_for('main.registration_confirmation'))

    return render_template('payment.html', form=form)

@main.route('/webshop')
def webshop():
    '''
    
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[{
            'price': 'price_1J02EpCA4AXKnreiLZQq2glE',
            'quantity': 1,
        }],
        mode = 'payment',
        success_url=url_for('.success', _external=True) + '?session_id={CHECKOUT}http://127.0.0.1:5000/success?session_id={CHECKOUT_SESSION_ID}',
        cancel_url=url_for('.webshop', _external=True)

    )
    '''
    def products():
        product = Product.Query
       # if product.active == True:


    return render_template('main/webshop.html', #checkout_public_key=current_app.config['STRIPE_PUBLIC_KEY'], 
                                                 #checkout_session_id=session['id']
                         )

@main.route('/success', methods=['GET'])
def success():
    return render_template('/main/success.html')


@main.route('/stripe_pay')
def stripe_pay():
    print('IN STRIPE_PAY FUNCTION')
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[{
            'price': 'price_1J02EpCA4AXKnreiLZQq2glE',
            'quantity': 1,
        }],
        mode = 'payment',
    success_url=url_for('.success', _external=True) + '?session_id={CHECKOUT_SESSION_ID}',
    cancel_url=url_for('.webshop', _external=True),

    )

    return {'checkout_session_id': session['id'], 
            'checkout_public_key': current_app.config['STRIPE_PUBLIC_KEY']}

@main.route('/stripe_webhook', methods=['POST'])
def stripe_webhook():
    print('WEBHOOK CALLED')

    if request.content_length > 1024 * 1024:
        print('REQUEST TO BIG')
        abort(400)
    payload = request.get_data()
    sig_header = request.environ.get('HTTP_STRIPE_SIGNATURE')
    endpoint_secret = current_app.config['STRIPE_ENDPIOINT_SECRET']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError as e:
        # Invalid Payload
        print('INVALID PAYLOAD')
        return {}, 400
    except stripe.errorSignatureVerificationError as e:
        print('INVALID SIGNATURE')
        return {}, 400

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        print('Success!!')
        print(session)

    return {},

app/templates/main/_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('.user', username=post.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ post.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
            <div class="post-author"><a href="{{ url_for('.user', username=post.author.username) }}">{{ post.author.username }}</a></div>
            <div class="post-body">{{ post.body }}</div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/main/_shop_items.html
<ul class="products">
    {% for product in products %}
    <li class="product">
        <div class="product-thumbnail">
            <a href="{{ url_for('.product', product=product.product_name) }}">
                <img class="img-rounded profile-thumbnail" src="{{ product.thumbnail(size=40) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
            
            <div class="post-body">{{ product.body }}</div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/main/admin_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Admin posts{% endblock %}

{% block page_content %}

<div>
    <h3>Editor</h3>
    {% if current_user.can(Permission.WRITE) %}
    {{ wtf.quick_form(form) }}
    {% endif %}
</div>
<div class="post-tab">
    <ul class="nav nav-tabs">
        <li></li>
    </ul>
    {% include '_posts.html' %}
</div>
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.index') }}
</div>

    
{% endif %}
    

{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/main/confirmation.html
{% extends "base.html" %}

{% block title %}You are registered!{% endblock %}


{% block page_content %}
<div class="page-header">
    <h1>You are now registered!</h1>
</div>
<h2>Reciept</h2>
<p>Order number: #00001</p>
<p>{{ session.get('name') }}</p>
<p>{{ session.get('email') }}</p>
<p>{{ session.get('tournament' ) }}
<p>Email sent! to {{ session.get('email') }. Check your inbox!}</p>
</p>
{% endblock %}

app/templates/main/edit_profile.html
{% extends "base.html" %}

{% block title %} Swordfish - {{ user.username.capitalize() [Edit Profile] }}{% endblock %}


{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/main/information.html
{% extends "base.html" %}
{% block title %} Information {% endblock %}

{%block page_content %}
<h1>Information about the event</h1>
{% endblock %}

app/templates/main/participants.html
{% extends "base.html" %}
{% block title %} Participants {% endblock %}

{%block page_content %}
<h1>List of friends and soon to be friends attending the event</h1>
{% endblock %}

app/templates/main/registration.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Registration{% endblock %}


{% block page_content %}
<div class="page-header">
    <h1>Register for Swordfish</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/main/success.html
{% extends "base.html" %}

{% block title %} Success!{% endblock %}

{% block page_content %}

<h1>You bought a thing!</h1>
    

{% endblock %}

app/templates/main/user.html
{% extends "base.html" %}

{% block title %} Swordfish - {{ user.name.capitalize() }}{% endblock %}


{% block page_content %}
<div class="page-header">
    <h1>Welcome, {{ user.name.capitalize() }}</h1>
    <ul>
        
        <li>Role: {{ user.role }}</li>
        <li>Country: {{ user.country }}</li>
        <li>Club: {{ user.club }} </li>
        

    </ul>
    {% if user == current_user %}
    <a class="btn btn-default" href="{{ url_for( 'auth.change_email_request' ) }}">Change Email</a>
    <a class="btn btn-default" href="{{ url_for( 'auth.change_password' )}}">Change Password</a>
    <a class="btn btn-default" href="{{ url_for('main.edit_profile') }}">Edit Profile</a>
    {% endif %}
    {% if current_user.is_administrator() %}
    <a class="btn btn-danger"
        href="{{ url_for('.edit_profile_admin', id=user.id) }}">
        Edit Profile [Admin]
    </a>
    {% endif %}
</div>
{% endblock %}

app/templates/main/webshop.html
{% extends "base.html" %}

{% block title %}Webshop{% endblock %}

{% block page_content %}

<h1>A product!</h1>
<a href="#" id="buy_now_btn" class="btn btn-primary">Checkout</a>

{% block script %}
{#
<script>
    const checkout_public_key = '{{checkout_public_key}}';
    const checkout_session_id = '{{checkout_session_id}}';
</script>
#}
<script src="https://js.stripe.com/v3"></script>
<script src="{{ url_for('static', filename='js/script-ajax.js')  }}"></script>
{% endblock %}

{% endblock %}

app/templates/main/workshops.html
{% extends "base.html" %}

{% block title %} Workshops{% endblock %}

{% block page_content %}

{% for each post in posts %}
    <h3>{{ post.title }}</h3>
    <p>{{ post.type_id }}</p>
    {% include '_posts.html' %}
    

{% endblock %}